# Generated by Django 5.0.1 on 2024-02-24 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polarity_predictor_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviereview',
            name='image_url',
            field=models.URLField(default='default_image_url'),
        ),
    ]
