# Generated by Django 5.0.1 on 2024-02-24 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polarity_predictor_app', '0002_moviereview_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviereview',
            name='image_url',
            field=models.URLField(null=True),
        ),
    ]
